image: jangrewe/gitlab-ci-android

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./ShakeToDo/gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./ShakeToDo/gradlew assembleDebug
  artifacts:
    paths:
    - ShakeToDo/app/build/outputs/apk/app-debug.apk